//LOADING
export const SET_LOADING = "SET_LOADING";

//DATA
export const SET_TIME_SERIES = "SET_TIME_SERIES";
export const SET_CONTENT_DATA = "SET_CONTENT_DATA";
export const SET_FILTERED_DATA = "SET_FILTERED_DATA";
export const CLEAR_SELECTED_MOVIE = "CLEAR_SELECTED_MOVIE";
export const SET_SELECTED_MOVIE = "SET_SELECTED_MOVIE";
